apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nginx-service
  namespace: default
spec:
  selector:
    app: backend-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: backend-php-service
  namespace: default
spec:
  selector:
    app: backend-php
  ports:
  - port: 9000
    targetPort: 9000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP